project:
  type: website
  output-dir: docs
  
website:
  title: "Modelos Predictivos Aplicados en la Agricultura"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/Victor-Hugo-Baldera/Labelstudio
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: " Programacion y Analisis de datos 2024, Baldera Victor, Fernandez Deyli, Santilla Alexander y Reyna Jamil"

format:
  html:
    theme: cerulean
    toc: true

editor: source

