project:
  type: website
  output-dir: docs
  
website:
  title: "PAD"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - projects.qmd
      - install.qmd
      - ejecucion.qmd
      - Aplicacion.qmd
      - Reco.qmd
      - Refe.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/Victor-Hugo-Baldera/Labelstudio
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: " Programacion y Analisis de datos 2024, Baldera Victor, Fernandez Deyli, Santilla Alexander y Reyna Jamil"

format:
  html:
    theme: LUX
    toc: true

editor: source

